ENV['COUNTRY_OF_STORE'] = 'India'
ENV['EMAIL'] = 'neetu.mogha@builder.ai'
ENV['NAMESPACE'] = 'freefree-238464'
ENV['DL_APP_NAME'] = 'ecommerceapp'
ENV['RUBY_ANALYTICS_TOKEN'] = 'ADvoiejfyI6IHGJbitMe9MGLbkPRxj6n'
ENV['HOST_URL'] = 'freefree-238464-ruby.b238464.dev.centralindia.az.svc.builder.ai/'
